# Generated by Django 4.2.16 on 2025-03-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heading',
            old_name='level',
            new_name='lavel',
        ),
    ]
